[package]
name = "nova-testkit"
version.workspace = true
edition.workspace = true

[dependencies]
nova-core = { workspace = true }
nova-ports = { workspace = true }
nova-adapter-mem = { workspace = true }
nova-matcher = { workspace = true }
nova-claim = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
