[package]
name = "nova-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nova-server"
path = "src/main.rs"

[dependencies]
nova-core = { workspace = true }
nova-ports = { workspace = true }
nova-adapter-mem = { workspace = true }
nova-matcher = { workspace = true }
nova-claim = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
